from crewai import Task
from agents import PrepAgents
from tools import json_tool

class PrepTasks(PrepAgents):
    def __init__(self):
        super().__init__()
        
    def machine_task(self):
        return Task(
        description=(
            "1. Collect and analyze the data from the SMT machines, "
                "such as temperature, speed, pressure, component type, etc.\n"
            "2. Adjust and optimize the machine's parameters according to the data "
                "and the feedback from other agents.\n"
            "3. Detect and report any abnormal or faulty conditions of the machine, "
                "such as jam, error, calibration overdue, etc.\n"
            "4. Execute the corrective actions generated by the process agents or "
                "the coordinator agents, such as stop, resume, reset, etc.\n"
        ),
        expected_output="A comprehensive content plan document "
            "with an outline, audience analysis, "
            "SEO keywords, and resources.",
        agent=self.machine_agent(),
        tools=[json_tool]
    )
    
    def process_task(self):
        return Task(
        description=(
            "1. Evaluate and optimize the process performance and "
                "quality based on the data and the feedback.\n"
            "2. Detect and diagnose any defects or failures on the PCB "
                "board within the same process stage, "
                "such as missing parts, wrong parts, misalignment, etc.\n"
            "3. Generate and propose corrective actions to prevent "
                "or reduce the defects or failures, "
                "such as change the machine parameters, stop the line, etc.\n"
        ),
        expected_output="A well-written blog post "
            "in markdown format, ready for publication, "
            "each section should have 2 or 3 paragraphs.",
        agent=self.process_agent(),
        
    )
    
    